export const Config = Object.freeze({
  visibleCount: 3,
  storageKey: "imdb-rapid-rater-v4",
  settingsKey: "imdb-rapid-rater-browser-settings-v1",
  recommendationPosterPreferenceKey: "imdb-rapid-rater-recommendation-posters-v1",
  recommendationRowsPreferenceKey: "imdb-rapid-rater-recommendation-rows-v1",
  animationMs: 110,
  dataUrl: "./data/movies.json",
  liveStatusUrl: "./api/imdb/status",
  aiStatusUrl: "./api/ai/status",
  aiModelsUrl: "./api/ai/models",
  recommendationsUrl: "./api/ai/recommendations",
  recommendationQueueUrl: "./api/ai/recommendations/queue",
  recommendationExclusionsUrl: "./api/account/recommendation-exclusions",
  titleMetadataUrl: "./api/title/",
  rateUrl: "./api/rate",
  notSeenUrl: "./api/account/not-seen",
  submitDelayMs: 750,
  skipKey: "`",
  ratingKeys: Object.freeze({
    "0": 10,
    "1": 1,
    "2": 2,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "7": 7,
    "8": 8,
    "9": 9
  })
});
